# Generated by Django 4.1.5 on 2023-01-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Phone',
            field=models.IntegerField(default=255, max_length=10),
            preserve_default=False,
        ),
    ]
