# Generated by Django 4.1.5 on 2023-01-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_app', '0002_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Email',
            field=models.CharField(default=255, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Password',
            field=models.CharField(default='off', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='Phone',
            field=models.IntegerField(),
        ),
    ]
