# Generated by Django 4.1.5 on 2023-01-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_app', '0003_user_email_user_password_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite', models.CharField(max_length=255)),
                ('admin', models.CharField(max_length=255)),
            ],
        ),
    ]
